# integers variable

old = 18
year = 2008
month = 1
date = 13

# float variables

loan = 1000.08
balance = 800.78
weight = 40.5
height = 158.5

# string variables

name = "Marianne"
schoolname = "DLL"
birthday = "January"
course = "BSIT "

# boolen variables

to_old = False
small = True
shorthair = False
haircolorblack = True

#prtint

print("my old is",old)
print("my year is",year)
print("my month is",month)
print("my date is",date)

print("my loan is",loan)
print("my balance is",balance)
print("my weight is", weight)
print("my height is", height)

print("my name is",name)
print("my schoolname is",schoolname)
print("my birthday is",birthday)
print("my course is",course)

print("i am to_old = ",to_old)
print("i am small = ",small)
print("i am shorthair = ",shorthair)
print("i am haircolorblack = ", haircolorblack)
