# + - Addition
# - - Suntraction
# - * Multiplication
# - / Division
# - // Floor Division
# - ** exponentation
# - % modulus

a = 13
b = 23

sum = a + b 
print("the sum of",a,"and",b,"is",sum)

c = 4
d = 8

diff = c - d
print("the diff of",c," and ",d,"is",diff)

e = 5
f = 8

sum = e * f
print("The sum of ",e," and ",e," is", sum)

g = 13
h = 8

sum = g / h
print("The sum of ",g," and ",h," is", sum)

i = 36
j = 6

sum = i // j
print("The sum of ",i," and ",j," is", sum)

k = 89
l = 8

sum = k ** l
print("The sum of ",k," and ",l," is", sum)

m = 68
n = 7

sum = m % n
print("The sum of ",m," and ",n," is", sum)

